### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by lcm1475** [X-SLAYER/flutter_overlay_window#109]
FlutterOverlayWindow.updateFlag(OverlayFlag.focusPointer);

E/flutter (25776): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method resizeOverlay on channel x-slayer/overlay)
E/flutter (25776): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (25776): <asynchronous suspension>
E/flutter (25776): #1      FlutterOverlayWindow.resizeOverlay (package:flutter_overlay_window/src/overlay_window.dart:107:24)
E/flutter (25776): <asynchronous suspension>
E/flutter (25776):

**Comment by lcm1475** [comment]
FlutterOverlayWindow.showOverlay
then
FlutterOverlayWindow.updateFlag(OverlayFlag.focusPointer);

E/flutter (25776): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method resizeOverlay on channel x-slayer/overlay)
E/flutter (25776): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (25776):
E/flutter (25776): https://github.com/X-SLAYER/flutter_overlay_window/issues/1 FlutterOverlayWindow.resizeOverlay (package:flutter_overlay_window/src/overlay_window.dart:107:24)
E/flutter (25776):
E/flutter (25776):
