### ISSUE TITLE
When I restart the phone and run the app in the background when receiving the call 'flutter_overlay_window', I get an error. 

### ISSUE THREAD

**Issue by alhelaly60** [X-SLAYER/flutter_overlay_window#137]
// 1. Restart your phone.
// 2. make a phone call (using the foreground_service package).
// 3. The app crashes with an error from flutter_overlay_window. app crashes with an error from flutter_overlay_window.

E/AndroidRuntime(28746): Process: com.example.call_me3, PID: 28746
E/AndroidRuntime(28746): java.lang.RuntimeException: Unable to create service flutter.overlay.window.flutter_overlay_window.OverlayService: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.dart.DartExecutor io.flutter.embedding.engine.FlutterEngine.getDartExecutor()' on a null object reference
E/AndroidRuntime(28746): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5086)
E/AndroidRuntime(28746): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime(28746): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)
E/AndroidRuntime(28746): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28746): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(28746): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(28746): 	at android.app.ActivityThread.main(ActivityThread.java:8762)
E/AndroidRuntime(28746): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28746): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime(28746): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(28746): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.dart.DartExecutor io.flutter.embedding.engine.FlutterEngine.getDartExecutor()' on a null object reference
E/AndroidRuntime(28746): 	at flutter.overlay.window.flutter_overlay_window.OverlayService.<init>(OverlayService.java:59)
E/AndroidRuntime(28746): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(28746): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(28746): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:74)
E/AndroidRuntime(28746): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5055)
E/AndroidRuntime(28746): 	... 9 more

**Comment by moradiyajay** [comment]
I'm facing the same issue.

**Comment by neo-xy** [comment]
nothing new on this topis?
