### ISSUE TITLE
The app cannot be launched while it is in the background.

### ISSUE THREAD

**Issue by lazyder** [X-SLAYER/flutter_overlay_window#143]
When the app is in the background and detects an incoming call/SMS, an error occurs while passing the data.
Error:
E/MethodChannel#x-slayer/overlay_channel(19672): Failed to handle method call
E/MethodChannel#x-slayer/overlay_channel(19672): android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { flg=0x30000000 cmp=com.overlay.test/flutter.overlay.window.flutter_overlay_window.OverlayService (has extras) }: app is in background uid UidRecord{f62b852 u0a394 RCVR bg:+16m44s128ms idle change:uncachedprocstateprocadj procs:0 seq(1253407,1250092)} caps=------
E/MethodChannel#x-slayer/overlay_channel(19672): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1956)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at android.app.ContextImpl.startService(ContextImpl.java:1911)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at android.content.ContextWrapper.startService(ContextWrapper.java:836)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at flutter.overlay.window.flutter_overlay_window.FlutterOverlayWindowPlugin.onMethodCall(FlutterOverlayWindowPlugin.java:110)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at android.os.Looper.loopOnce(Looper.java:224)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at android.os.Looper.loop(Looper.java:318)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at android.app.ActivityThread.main(ActivityThread.java:8763)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
E/MethodChannel#x-slayer/overlay_channel(19672): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by NoahFlatfish** [comment]
same problem listner don't work in background

**Comment by jbergloda1** [comment]
same problem

**Comment by mohamadElEaswy** [comment]
any updates?
