### ISSUE TITLE
Resize Overlay is not working

### ISSUE THREAD

**Issue by hemandroid** [X-SLAYER/flutter_overlay_window#16]
Hi there,

Unable to use the feature of resize overlay

```
D/EGL_emulation(13076): app_time_stats: avg=6515.98ms min=6515.98ms max=6515.98ms count=1
E/flutter (13076): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method resizeOverlay on channel x-slayer/overlay)
E/flutter (13076): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (13076): <asynchronous suspension>
E/flutter (13076): #1      FlutterOverlayWindow.resizeOverlay (package:flutter_overlay_window/flutter_overlay_window.dart:110:24)
E/flutter (13076): <asynchronous suspension>
E/flutter (13076): #2      _MessangerChatHeadState.resize (package:flutter_overlay_window_example/overlays/messanger_chathead.dart:21:5)
E/flutter (13076): <asynchronous suspension>
E/flutter (13076): 
```

This was the code changes which I did

```
class MessangerChatHead extends StatefulWidget {
  const MessangerChatHead({Key? key}) : super(key: key);

  @override
  State<MessangerChatHead> createState() => _MessangerChatHeadState();
}

class _MessangerChatHeadState extends State<MessangerChatHead> {
  Color color = const Color(0xFFFFFFFF);

  @override
  void initState() {
    super.initState();
    resize();
  }

  resize() async{
    await FlutterOverlayWindow.resizeOverlay(80, 120);
  }

  @override
  Widget build(BuildContext context) {
    return Material(
        color: Colors.transparent,
        elevation: 0.0,
        child: FloatingActionButton(
          elevation: 0,

          splashColor: Colors.transparent,
          child: const Text('02:00'),
          onPressed: () {
          FlutterOverlayWindow.closeOverlay();
        },)
    );
  }
}
```

**Comment by ahmedradwan18** [comment]
have you found a solution?

**Comment by X-SLAYER** [comment]
check the example of the latest version on how to reside it
