### ISSUE TITLE
哥们你在pub.dev上的包似乎没更新

### ISSUE THREAD

**Issue by coolight7** [X-SLAYER/flutter_overlay_window#36]
* 今天先是在pub.dev上发现了这个好东西，使用时可以正常打开悬浮窗，但却无法关闭，一调用FlutterOverlayWindow.closeOverlay()就报错：
```
E/flutter ( 7080): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel x-slayer/overlay)
E/flutter ( 7080): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter ( 7080): <asynchronous suspension>
E/flutter ( 7080): #1      FlutterOverlayWindow.closeOverlay (package:flutter_overlay_window/flutter_overlay_window.dart:83:24)
```
* 后来直接下载github上的示例却能打开悬浮窗也能关闭，于是开始对比代码区别，最终发现使用pub.dev上的包时就会出错：
```
flutter_overlay_window: ^0.3.2
```
直接下载github上的包到本地使用就正常：
```
  flutter_overlay_window: 
    path: ./lib/plugins/flutter_overlay_window/{本地包路径}
```

**Comment by X-SLAYER** [comment]
[flutter_overlay_window v 0.3.3](https://pub.dev/packages/flutter_overlay_window/)
