### ISSUE TITLE
Showing overlay from background

### ISSUE THREAD

**Issue by mulaRahul** [X-SLAYER/flutter_overlay_window#42]
Thanks for this awesome package!

I had no problem showing/closing an overlay when the app is in the foreground or paused. But, in my use case, I attempted to show an overlay from a background task (_workmanager_). And I got the `java.lang.IllegalStateException: Not allowed to start service Intent` exception.

<details>
<summary>Logs</summary>

```
...
Background start not allowed: service Intent { flg=0x30000000 cmp=com.example.overlay_test/flutter.overlay.window.flutter_overlay_window.OverlayService } to com.example.overlay_test/flutter.overlay.window.flutter_overlay_window.OverlayService from pid=10481 uid=10125 pkg=com.example.overlay_test startFg?=false

Failed to handle method call
    java.lang.IllegalStateException: Not allowed to start service Intent { flg=0x30000000 cmp=com.example.overlay_test/flutter.overlay.window.flutter_overlay_window.OverlayService }: app is in background uid UidRecord{4e22f0e u0a125 CEM  idle change:cached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1715)
        at android.app.ContextImpl.startService(ContextImpl.java:1670)
        at android.content.ContextWrapper.startService(ContextWrapper.java:720)
        at flutter.overlay.window.flutter_overlay_window.FlutterOverlayWindowPlugin.onMethodCall(FlutterOverlayWindowPlugin.java:99)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

errorCode: error, errorMessage: Not allowed to start service Intent { flg=0x30000000 cmp=com.example.overlay_test/flutter.overlay.window.flutter_overlay_window.OverlayService }: app is in background uid UidRecord{4e22f0e u0a125 CEM  idle change:cached procs:1 seq(0,0,0)}
...
```
</details>

Now I have zero experience with Java but as a programmer, I just took the error and pasted it onto google. After going through some _stackoverflows_ I found out that the `IntentService` used [here](https://github.com/X-SLAYER/flutter_overlay_window/blob/a53c70d5914c11c3d268e3b94794d29647e4a743/android/src/main/java/flutter/overlay/window/flutter_overlay_window/FlutterOverlayWindowPlugin.java#L99) -

```java
final Intent intent = new Intent(context, OverlayService.class);
intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
intent.addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);
context.startService(intent);
```

is deprecated and not allowed above Android 8.0 when the app is in background, or something along those lines.

As for fixes, I found that the new [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler) can be used or the service can be moved to foreground `context.startForegroundService(intent);`. Of course, I'm not familiar with the internals that's why I can't tell which parts need to be affected after applying the above fixes.

If possible, please address the issue. Else, if possible, please provide me some helpers/pointers on the subject so that I can work on the same.

**Comment by mulaRahul** [comment]
NVM, I've implemented the above according to my need. Thanks anyway!
